version: 3
extends: "https://api.github.com/repos/medology/Scripts/contents/Pull%20Approve/base.pullapprove.yml?ref=master"
pullapprove_conditions:
  - 
    condition: "base.ref == 'master'"
    unmet_status: failure
    explanation: "PullApprove is not configured for this branch"
  - 
    condition: "'[DO NOT REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - 
    condition: "state == 'open'"
    explanation: "PR must be open to be reviewed"
    unmet_status: failure
  - 
    condition: "'ci/circleci: test' in statuses.succeeded or 'Force Review' in labels"
    unmet_status: pending
    explanation: "Tests and builds must pass before requesting review"
  - 
    condition: "'continuous-integration/styleci/pr' in statuses.succeeded or 'Force Review' in labels"
    unmet_status: pending
    explanation: "StyleCI must pass before requesting review"

