version: '3'

services:
  app:
    image: chekote/php:7.0.8
    volumes:
      - ..:/data
    entrypoint:
      - php-fpm7.0
    env_file: .env

  web:
    build: nginx
    volumes:
      - ..:/data
    env_file: .env
    ports:
      - 80:80
      - 443:443

  chrome:
    image: ${SELENIUM_IMAGE}
    depends_on:
      - web
    environment:
        SCREEN_WIDTH: 1600
        SCREEN_HEIGHT: 1200
        no_proxy: localhost
    links:
      - web
      - web:findalab.local
    volumes:
      - /dev/shm:/dev/shm
      - ..:/data
    env_file: .env
    ports:
      - 5900:5900

networks:
  default:
    driver: bridge
