version: '2'

services:
  web:
    image: php:7.0.10-apache
    volumes:
      - ..:/var/www
      - ../../dist:/var/www/html/dist
      - ../../js:/var/www/html/js
      - ../../template:/var/www/html/template
    ports:
      - 80:80

  chrome:
    image: selenium/standalone-chrome-debug:2.53.0
    depends_on:
      - web
    environment:
        - no_proxy:localhost
    links:
      - web
      - web:findalab.local
    volumes:
      - /dev/shm:/dev/shm
      - ..:/data
    ports:
      - 5900:5900
